CREATE TABLE `performance_actions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_id` text NOT NULL,
	`assignment_id` integer NOT NULL,
	`action_type` text NOT NULL,
	`title` text NOT NULL,
	`description` text,
	`owner` text,
	`start_date` text,
	`target_date` text,
	`check_dates` text,
	`employee_comment` text,
	`manager_comment` text,
	`old_score` integer,
	`new_score` integer,
	`reason` text,
	`acknowledged` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'Taslak' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `performance_assignments` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_id` text NOT NULL,
	`cycle_id` integer NOT NULL,
	`employee_id` integer NOT NULL,
	`employee_name` text NOT NULL,
	`department_snapshot` text NOT NULL,
	`position_snapshot` text NOT NULL,
	`manager_snapshot` text,
	`goal_score` integer DEFAULT 0 NOT NULL,
	`kpi_score` integer DEFAULT 0 NOT NULL,
	`competency_score` integer DEFAULT 0 NOT NULL,
	`manager_score` integer DEFAULT 0 NOT NULL,
	`self_score` integer DEFAULT 0 NOT NULL,
	`feedback_360_score` integer DEFAULT 0 NOT NULL,
	`overall_score` integer DEFAULT 0 NOT NULL,
	`calibrated_score` integer,
	`performance_class` text DEFAULT 'E' NOT NULL,
	`status` text DEFAULT 'Başlamadı' NOT NULL,
	`locked` integer DEFAULT false NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `performance_assignment_cycle_employee_unique` ON `performance_assignments` (`cycle_id`,`employee_id`);--> statement-breakpoint
CREATE TABLE `performance_competencies` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_id` text NOT NULL,
	`assignment_id` integer,
	`name` text NOT NULL,
	`category` text DEFAULT 'Temel Yetkinlik' NOT NULL,
	`position` text,
	`description` text,
	`weight` integer DEFAULT 0 NOT NULL,
	`self_score` integer DEFAULT 0 NOT NULL,
	`manager_score` integer DEFAULT 0 NOT NULL,
	`final_score` integer DEFAULT 0 NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `performance_cycles` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_id` text NOT NULL,
	`name` text NOT NULL,
	`cycle_type` text DEFAULT 'Yıllık' NOT NULL,
	`start_date` text NOT NULL,
	`end_date` text NOT NULL,
	`review_start_date` text NOT NULL,
	`review_end_date` text NOT NULL,
	`departments` text DEFAULT '[]' NOT NULL,
	`min_tenure_months` integer DEFAULT 3 NOT NULL,
	`goal_weight` integer DEFAULT 40 NOT NULL,
	`kpi_weight` integer DEFAULT 30 NOT NULL,
	`competency_weight` integer DEFAULT 20 NOT NULL,
	`manager_weight` integer DEFAULT 10 NOT NULL,
	`self_weight` integer DEFAULT 0 NOT NULL,
	`feedback_360_weight` integer DEFAULT 0 NOT NULL,
	`reminder_days` text DEFAULT '10,5,3,0' NOT NULL,
	`status` text DEFAULT 'Aktif' NOT NULL,
	`created_by` text NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `performance_cycle_company_name_unique` ON `performance_cycles` (`company_id`,`name`);--> statement-breakpoint
CREATE TABLE `performance_feedback` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_id` text NOT NULL,
	`assignment_id` integer NOT NULL,
	`reviewer_email` text NOT NULL,
	`reviewer_type` text NOT NULL,
	`score` integer DEFAULT 0 NOT NULL,
	`strengths` text,
	`development_areas` text,
	`comment` text,
	`anonymous` integer DEFAULT false NOT NULL,
	`status` text DEFAULT 'Taslak' NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `performance_metrics` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`company_id` text NOT NULL,
	`cycle_id` integer,
	`assignment_id` integer,
	`metric_type` text NOT NULL,
	`source_type` text DEFAULT 'Bireysel' NOT NULL,
	`name` text NOT NULL,
	`code` text,
	`description` text,
	`department` text,
	`position` text,
	`unit` text DEFAULT '%' NOT NULL,
	`direction` text DEFAULT 'Yüksek değer iyi' NOT NULL,
	`start_value` integer DEFAULT 0 NOT NULL,
	`target_value` integer DEFAULT 100 NOT NULL,
	`actual_value` integer DEFAULT 0 NOT NULL,
	`minimum_value` integer,
	`maximum_value` integer,
	`weight` integer DEFAULT 0 NOT NULL,
	`priority` text DEFAULT 'Orta' NOT NULL,
	`data_source` text DEFAULT 'Manuel' NOT NULL,
	`frequency` text,
	`approver` text,
	`start_date` text,
	`end_date` text,
	`score` integer DEFAULT 0 NOT NULL,
	`status` text DEFAULT 'Aktif' NOT NULL,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
