"use client";
import {useEffect,useMemo,useState} from "react";

type Req={id:number;employeeId:number;requestType:string;requestDate:string;approvedAmount:number;approvedInstallments:number;collectedAmount:number;balance:number;status:string;firstDeductionMonth:string};
type Installment={id:number;requestId:number;sequence:number;dueMonth:string;amount:number;status:string;payrollTransferred:boolean};
type Payment={id:number;requestId:number;paymentType:string;amount:number;paymentDate:string;method?:string;receiptNo?:string};
const money=(n:number)=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(n);

export default function EmployeeAdvancePanel({employeeId,employeeStatus}:{employeeId:number;employeeStatus:string}){
 const[requests,setRequests]=useState<Req[]>([]),[installments,setInstallments]=useState<Installment[]>([]),[payments,setPayments]=useState<Payment[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/advances").then(async r=>({ok:r.ok,data:await r.json()})).then(({ok,data})=>{if(!ok)return;const own=(data.requests||[]).filter((x:Req)=>x.employeeId===employeeId),ids=new Set<number>(own.map((x:Req)=>x.id));setRequests(own);setInstallments((data.installments||[]).filter((x:Installment)=>ids.has(x.requestId)));setPayments((data.payments||[]).filter((x:Payment)=>ids.has(x.requestId)))}).finally(()=>setLoading(false))},[employeeId]);
 const currentMonth=new Date().toISOString().slice(0,7),active=requests.filter(x=>["Aktif","Ödeme Bekliyor","Onay Bekliyor","Revizyon"].includes(x.status)),open=active.reduce((s,x)=>s+x.balance,0),planned=installments.filter(x=>x.status==="Planlandı"),next=planned.find(x=>x.dueMonth>=currentMonth)||planned[0],monthly=planned.filter(x=>x.dueMonth===next?.dueMonth).reduce((s,x)=>s+x.amount,0),paid=payments.filter(x=>x.paymentType!=="Şirket Ödemesi").reduce((s,x)=>s+x.amount,0),history=useMemo(()=>requests.slice().sort((a,b)=>b.requestDate.localeCompare(a.requestDate)),[requests]);
 if(loading)return <div className="employee-finance-loading">Borç ve avans bilgileri yükleniyor…</div>;
 return <div className="employee-finance"><div className="employee-finance-head"><div><h3>04 · Borç & Avans</h3><p>Sicil kartına bağlı güncel finansal yükümlülükler ve hareket geçmişi</p></div><span className={open>0?"finance-pill open":"finance-pill"}>{open>0?"Açık bakiye var":"Borç bulunmuyor"}</span></div>{employeeStatus!=="Aktif"&&open>0&&<div className="exit-debt-warning"><b>İşten çıkış / mahsup kontrolü</b><span>Bu personelin {money(open)} açık borç/avans bakiyesi bulunuyor. Son maaş, izin, kıdem ve ihbar hesabında yetkili onayıyla mahsup edilmelidir.</span></div>}<div className="employee-finance-cards"><article><small>Toplam Açık Borç</small><strong>{money(open)}</strong></article><article><small>Aktif Kayıt</small><strong>{active.length}</strong></article><article><small>Aylık Kesinti</small><strong>{money(monthly)}</strong></article><article><small>Kalan Taksit</small><strong>{planned.length}</strong></article><article><small>Sonraki Kesinti</small><strong>{next?.dueMonth||"—"}</strong></article><article><small>Toplam Tahsilat</small><strong>{money(paid)}</strong></article></div><div className="employee-finance-table"><div className="ef-row head"><span>Tür</span><span>Tarih</span><span>Onaylanan</span><span>Kalan</span><span>Durum</span></div>{history.length?history.map(x=><div className="ef-row" key={x.id}><span><b>{x.requestType}</b><small>#{x.id} · {x.approvedInstallments} taksit</small></span><span>{x.requestDate}</span><span>{money(x.approvedAmount)}</span><span><b>{money(x.balance)}</b></span><span><i>{x.status}</i></span></div>):<div className="employee-finance-empty">Bu personele ait borç veya avans kaydı bulunmuyor.</div>}</div></div>
}
