"use client";
import {FormEvent,useState} from "react";

type Goal={id:number;name:string;actualValue:number;targetValue:number};
type Employee={id:number;firstName:string;lastName:string;department:string;position:string;status:string};
type Cycle={id:number;name:string;status:string};

export default function GoalActionModal({mode,goal,employees,cycles,close,done}:{mode:"checkpoint"|"copy"|"carry";goal:Goal;employees:Employee[];cycles:Cycle[];close:()=>void;done:(message:string)=>void}){
  const[saving,setSaving]=useState(false),[error,setError]=useState("");
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");const data=new FormData(e.currentTarget),values=Object.fromEntries(data.entries()),payload=mode==="checkpoint"?{action:"updateMetric",id:goal.id,actualValue:Number(values.actualValue),checkpoint:{date:values.date,managerComment:values.managerComment,employeeComment:values.employeeComment,riskStatus:values.riskStatus,action:values.followupAction}}:{action:mode==="copy"?"goalCopy":"goalCarry",sourceMetricId:goal.id,targetCycleId:Number(values.targetCycleId),employeeIds:mode==="copy"?data.getAll("employeeIds").map(Number):undefined};const r=await fetch("/api/performance",{method:mode==="checkpoint"?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),j=await r.json();setSaving(false);if(!r.ok){setError(j.error||"İşlem tamamlanamadı");return}done(mode==="checkpoint"?"Ara kontrol kaydedildi":mode==="copy"?`${j.created} çalışana hedef kopyalandı`:"Hedef sonraki döneme devredildi")}
  const title=mode==="checkpoint"?"Hedef Ara Kontrolü":mode==="copy"?"Hedefi Çalışanlara Kopyala":"Hedefi Sonraki Döneme Devret";
  return <div className="modal-backdrop goal-action-backdrop"><form className="record-modal goal-action-form" onSubmit={submit}><header><div><span>HEDEF YÖNETİMİ</span><h2>{title}</h2><p>{goal.name}</p></div><button type="button" onClick={close}>×</button></header>{mode==="checkpoint"?<div className="form-grid"><label>Kontrol Tarihi<input name="date" type="date" required/></label><label>Gerçekleşen Değer<input name="actualValue" type="number" step="0.01" defaultValue={goal.actualValue} required/></label><label>Risk Durumu<select name="riskStatus"><option>Normal</option><option>Riskli</option><option>Gecikmiş</option></select></label><label>Aksiyon<input name="followupAction" placeholder="Takip aksiyonu"/></label><label className="wide">Yönetici Yorumu<textarea name="managerComment" placeholder="İlerleme değerlendirmesi"/></label><label className="wide">Çalışan Yorumu<textarea name="employeeComment" placeholder="Çalışanın açıklaması"/></label></div>:<div className="form-grid"><label className="wide">Hedef Dönem<select name="targetCycleId" required defaultValue=""><option value="">Dönem seçin</option>{cycles.map(x=><option key={x.id} value={x.id}>{x.name} · {x.status}</option>)}</select></label>{mode==="copy"&&<label className="wide">Çalışanlar<select name="employeeIds" multiple required size={Math.min(8,Math.max(4,employees.length))}>{employees.filter(x=>x.status==="Aktif").map(x=><option key={x.id} value={x.id}>{x.firstName} {x.lastName} – {x.department} – {x.position}</option>)}</select><small>Birden fazla seçim için Ctrl / Cmd tuşunu kullanın.</small></label>}<p className="goal-preserve-note">Kaynak hedef korunur; yeni kayıt kaynak hedefe bağlı olarak oluşturulur.</p></div>}{error&&<p className="form-error">{error}</p>}<footer><button type="button" onClick={close}>Vazgeç</button><button className="primary" disabled={saving}>{saving?"Kaydediliyor…":"İşlemi Tamamla"}</button></footer></form></div>
}
