"use client";
import { FormEvent, useEffect, useState } from "react";
import "./number-series-manager.css";
type Series={id:number;seriesType:string;label:string;prefix:string;startNumber:number;lastUsed:number;digits:number;nextNumber:number;nextValue:string};
export default function NumberSeriesManager({act}:{act:(message:string)=>void}){
 const[rows,setRows]=useState<Series[]>([]),[canEdit,setCanEdit]=useState(false),[selected,setSelected]=useState<Series|null>(null),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/number-series",{cache:"no-store"}),j=await r.json();if(r.ok){setRows(Array.isArray(j.series)?j.series:[]);setCanEdit(Boolean(j.canEdit));setError("")}else setError(j.error||"Numara serileri yüklenemedi")}
 useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
  load()
 },[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const data=Object.fromEntries(new FormData(e.currentTarget).entries()),r=await fetch("/api/number-series",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({...data,seriesType:selected.seriesType})}),j=await r.json();if(!r.ok){setError(j.error||"Seri güncellenemedi");return}setSelected(null);await load();act("Numara serisi güncellendi ve audit kaydına işlendi")}
 return <section className="number-series-page"><header><div><span>SİSTEM PARAMETRELERİ</span><h2>Numara Serileri</h2><p>Aktif şirketin otomatik kodlarını tek merkezden yönetin.</p></div><b>{canEdit?"Süper Admin düzenleme yetkisi":"Salt okunur görünüm"}</b></header>{error&&<p className="series-error">{error}</p>}<div className="series-grid">{rows.map(row=><article key={row.seriesType}><div><small>{row.label}</small><strong>{row.nextValue}</strong></div><dl><div><dt>Ön Ek</dt><dd>{row.prefix}</dd></div><div><dt>Başlangıç</dt><dd>{row.startNumber}</dd></div><div><dt>Son Kullanılan</dt><dd>{row.lastUsed}</dd></div><div><dt>Sonraki</dt><dd>{row.nextNumber}</dd></div><div><dt>Basamak</dt><dd>{row.digits}</dd></div></dl><button disabled={!canEdit} onClick={()=>setSelected(row)}>{canEdit?"Seriyi Düzenle":"Yalnızca Süper Admin"}</button></article>)}</div>{selected&&<div className="modal-backdrop"><form className="record-modal series-modal" onSubmit={save}><header><div><span>NUMARA SERİSİ</span><h2>{selected.label}</h2><p>Kullanılmış bir numaraya geri dönülemez.</p></div><button type="button" onClick={()=>setSelected(null)}>×</button></header><div className="form-grid"><label className="field"><span>Ön Ek</span><input name="prefix" defaultValue={selected.prefix} required/></label><label className="field"><span>Başlangıç Numarası</span><input name="startNumber" type="number" min="1" defaultValue={selected.startNumber} required/></label><label className="field"><span>Son Kullanılan Numara</span><input value={selected.lastUsed} readOnly/></label><label className="field"><span>Sonraki Numara</span><input name="nextNumber" type="number" min={selected.lastUsed+1} defaultValue={selected.nextNumber} required/></label><label className="field"><span>Basamak Sayısı</span><input name="digits" type="number" min="1" max="12" defaultValue={selected.digits} required/></label></div><footer><button type="button" onClick={()=>setSelected(null)}>İptal</button><button className="primary">Kaydet</button></footer></form></div>}</section>
}
