"use client";
import { FormEvent, PointerEvent as ReactPointerEvent, RefObject, useEffect, useMemo, useRef, useState } from "react";
import OrganizationCopyModal from "./organization-copy-modal";
import "./organization-hierarchy.css";

type Company={id:string;name:string};
type Department={id:number;companyId:string;name:string;code:string;parentDepartmentId?:number|null;managerName?:string;status:string};
type Position={id:number;companyId:string;departmentId:number;title:string;code:string;reportsToId?:number|null;level:string;status:string};
type Employee={id:number;companyId:string;firstName:string;lastName:string;departmentId?:number|null;department:string;positionId?:number|null;position:string;manager?:string;secondManager?:string;actingManager?:string;delegationStart?:string;delegationEnd?:string;employeeNo?:string;employeeType?:string;email?:string;startDate?:string;endDate?:string|null;status:string};
type View="chart"|"departments"|"positions"|"list";
type Issue={kind:string;text:string;employee?:Employee};
const norm=(v?:string)=>String(v||"").trim().toLocaleLowerCase("tr-TR").replace(/\s+/g," ");
const full=(e:Employee)=>`${e.firstName} ${e.lastName}`.trim();
const active=(e:Employee)=>norm(e.status)==="aktif"&&(!e.endDate||e.endDate>new Date().toISOString().slice(0,10));
const safe=(v:unknown)=>String(v??"").replace(/[\\()]/g," ").replace(/[^\x20-\x7E]/g,"?");
function download(blob:Blob,name:string){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

export default function OrganizationManager({act,initialView="chart"}:{act:(s:string)=>void;initialView?:"chart"|"departments"|"positions"}){
 const[companies,setCompanies]=useState<Company[]>([]),[departments,setDepartments]=useState<Department[]>([]),[positions,setPositions]=useState<Position[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[view,setView]=useState<View>(initialView),[scope,setScope]=useState<"company"|"group">("company"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[departmentFilter,setDepartmentFilter]=useState(""),[positionFilter,setPositionFilter]=useState(""),[managerFilter,setManagerFilter]=useState(""),[typeFilter,setTypeFilter]=useState(""),[statusFilter,setStatusFilter]=useState("Aktif"),[showEmpty,setShowEmpty]=useState(true),[collapsed,setCollapsed]=useState<Set<number>>(new Set()),[zoom,setZoom]=useState(.9),[pan,setPan]=useState({x:0,y:0}),[selected,setSelected]=useState<Employee|null>(null),[issuesOpen,setIssuesOpen]=useState(false),[copyOpen,setCopyOpen]=useState(false),[modal,setModal]=useState<"department"|"position"|null>(null),[editing,setEditing]=useState<Department|Position|null>(null);
 const drag=useRef<{x:number;y:number;px:number;py:number}|null>(null),canvas=useRef<HTMLDivElement>(null);
 async function load(next=scope){setLoading(true);try{const r=await fetch(`/api/organization${next==="group"?"?scope=group":""}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.error||"Organizasyon verileri yüklenemedi");setCompanies(Array.isArray(j.companies)?j.companies:[]);setDepartments(Array.isArray(j.departments)?j.departments:[]);setPositions(Array.isArray(j.positions)?j.positions:[]);setEmployees(Array.isArray(j.employees)?j.employees:[]);setError("")}catch(e){setError(e instanceof Error?e.message:"Veriler yüklenemedi")}finally{setLoading(false)}}
 useEffect(()=>{load();const sync=()=>load();window.addEventListener("employees-updated",sync);window.addEventListener("departments-updated",sync);return()=>{window.removeEventListener("employees-updated",sync);window.removeEventListener("departments-updated",sync)}},[]);
 const managerOf=(e:Employee,list=employees)=>{const key=norm(e.manager);return key?list.find(x=>x.companyId===e.companyId&&[norm(full(x)),norm(x.employeeNo),norm(x.email)].includes(key)):undefined};
 const filtered=useMemo(()=>employees.filter(e=>{const hay=norm(`${full(e)} ${e.employeeNo} ${e.department} ${e.position} ${e.manager}`);return(!query||hay.includes(norm(query)))&&(!departmentFilter||String(e.departmentId)===departmentFilter)&&(!positionFilter||e.position===positionFilter)&&(!managerFilter||norm(e.manager)===norm(managerFilter))&&(!typeFilter||e.employeeType===typeFilter)&&(!statusFilter||(statusFilter==="Aktif"?active(e):e.status===statusFilter))}),[employees,query,departmentFilter,positionFilter,managerFilter,typeFilter,statusFilter]);
 const filteredIds=new Set(filtered.map(e=>e.id)),displayEmployees=query||departmentFilter||positionFilter||managerFilter||typeFilter||statusFilter!=="Aktif"?employees.filter(e=>filteredIds.has(e.id)||filtered.some(f=>managerOf(f)?.id===e.id)):employees.filter(active);
 const direct=(e:Employee,list=displayEmployees)=>list.filter(x=>managerOf(x,list)?.id===e.id);
 const roots=(list:Employee[])=>list.filter(e=>!managerOf(e,list)||managerOf(e,list)?.id===e.id);
 const filled=positions.filter(p=>employees.some(e=>active(e)&&e.companyId===p.companyId&&(e.positionId===p.id||(e.departmentId===p.departmentId&&e.position===p.title)))).length;
 const issues=useMemo<Issue[]>(()=>{const out:Issue[]=[];employees.filter(active).forEach(e=>{if(!e.departmentId)out.push({kind:"Departman",text:`${full(e)} için departman tanımlı değil`,employee:e});if(!e.positionId&&!e.position)out.push({kind:"Pozisyon",text:`${full(e)} için pozisyon tanımlı değil`,employee:e});if(e.manager&&!managerOf(e))out.push({kind:"Yönetici",text:`${full(e)} için “${e.manager}” sicil kartlarında bulunamadı`,employee:e});if(managerOf(e)?.id===e.id)out.push({kind:"Bağlantı",text:`${full(e)} kendisine bağlı görünüyor`,employee:e})});departments.filter(d=>d.status==="Aktif"&&!d.managerName&&!employees.some(e=>e.companyId===d.companyId&&e.departmentId===d.id&&direct(e).length)).forEach(d=>out.push({kind:"Departman yöneticisi",text:`${d.name} departmanında yönetici tanımlı değil`}));const codes=new Set<string>();positions.forEach(p=>{const k=`${p.companyId}:${p.code}`;if(codes.has(k))out.push({kind:"Pozisyon kodu",text:`${p.code} kodu aynı şirkette birden fazla kullanılıyor`});codes.add(k)});return out},[employees,departments,positions]);
 function changeScope(value:"company"|"group"){setScope(value);setSelected(null);setCollapsed(new Set());load(value)}
 function toggle(id:number){setCollapsed(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 function pointerDown(e:ReactPointerEvent){if((e.target as HTMLElement).closest("button"))return;drag.current={x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}
 function pointerMove(e:ReactPointerEvent){if(drag.current)setPan({x:drag.current.px+e.clientX-drag.current.x,y:drag.current.py+e.clientY-drag.current.y})}
 function pointerUp(){drag.current=null}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries()),r=await fetch("/api/organization",{method:editing?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...data,kind:modal,id:editing?.id})}),j=await r.json();if(!r.ok){setError(j.error||"Kayıt tamamlanamadı");return}setModal(null);setEditing(null);await load();act("Organizasyon kaydı kaydedildi")}
 async function remove(kind:"department"|"position",id:number,name:string){if(!confirm(`“${name}” kaydı silinsin mi?`))return;const r=await fetch(`/api/organization?kind=${kind}&id=${id}`,{method:"DELETE"}),j=await r.json();if(!r.ok){setError(j.error||"Bağlı kayıtları taşıdıktan sonra silebilirsiniz");return}await load();act("Organizasyon kaydı silindi")}
 const exportRows=filtered.map(e=>[full(e),e.position||"—",e.department||"—",e.manager||"Atanmamış",companies.find(c=>c.id===e.companyId)?.name||e.companyId,e.status]);
 function excel(){const rows=[["Çalışan","Pozisyon","Departman","Yönetici","Şirket","Durum"],...exportRows];download(new Blob(["\ufeff"+rows.map(r=>r.map(v=>`\"${String(v).replaceAll('"','""')}\"`).join("\t")).join("\n")],{type:"application/vnd.ms-excel"}),`Organizasyon_Semasi_${new Date().toISOString().slice(0,10)}.xls`)}
 function pdf(){const lines=["MEGA HRMS Professional","Organizasyon Semasi Raporu",`Olusturulma: ${new Date().toLocaleString("tr-TR")}`,`Filtre: ${query||"Tumu"}`,...exportRows.map(r=>r.join(" | "))];const stream=`BT /F1 9 Tf 35 560 Td ${lines.slice(0,32).map((l,i)=>`${i?"0 -16 Td ":""}(${safe(l).slice(0,150)}) Tj`).join("\n")} ET`,objs=["","<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [4 0 R] /Count 1 >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 842 595] /Resources << /Font << /F1 3 0 R >> >> /Contents 5 0 R >>",`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let out="%PDF-1.4\n",offset=[0];for(let i=1;i<objs.length;i++){offset[i]=out.length;out+=`${i} 0 obj\n${objs[i]}\nendobj\n`}const x=out.length;out+=`xref\n0 ${objs.length}\n0000000000 65535 f \n${offset.slice(1).map(v=>String(v).padStart(10,"0")+" 00000 n \n").join("")}trailer\n<< /Size ${objs.length} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;download(new Blob([out],{type:"application/pdf"}),`Organizasyon_Semasi_${new Date().toISOString().slice(0,10)}.pdf`)}
 function png(){const rows=exportRows.slice(0,60),h=150+rows.length*26,esc=(s:string)=>s.replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]!)),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1400" height="${h}"><rect width="100%" height="100%" fill="#f6f8fb"/><text x="55" y="55" font-family="Arial" font-size="28" font-weight="700" fill="#10263f">MEGA HRMS Professional</text><text x="55" y="90" font-family="Arial" font-size="20" fill="#147d83">Organizasyon Şeması</text>${rows.map((r,i)=>`<rect x="45" y="${120+i*26}" width="1310" height="22" rx="5" fill="${i%2?"#fff":"#edf3f6"}"/><text x="55" y="${136+i*26}" font-family="Arial" font-size="13" fill="#23384e">${esc(r.join("   •   "))}</text>`).join("")}</svg>`;const img=new Image();img.onload=()=>{const c=document.createElement("canvas");c.width=1400;c.height=h;c.getContext("2d")!.drawImage(img,0,0);c.toBlob(b=>b&&download(b,`Organizasyon_Semasi_${new Date().toISOString().slice(0,10)}.png`))};img.src="data:image/svg+xml;charset=utf-8,"+encodeURIComponent(svg)}
 return <div className="workspace org-workspace"><div className="workspace-head"><div><span>MEGA HRMS / ORGANİZASYON</span><h2>Organizasyon Yönetimi</h2><p>Gerçek sicil kartlarından üretilen yönetim hiyerarşisi ve kadro görünümü</p></div><div className="org-actions"><button onClick={()=>setCopyOpen(true)}>⧉ Başka Şirketten Kopyala</button><button onClick={()=>{setEditing(null);setModal("department")}}>＋ Departman</button><button className="primary" onClick={()=>{setEditing(null);setModal("position")}}>＋ Pozisyon</button></div></div>
  <section className="org-commandbar"><label><span>Şema Kapsamı</span><select value={scope} onChange={e=>changeScope(e.target.value as "company"|"group")}><option value="company">Aktif Şirket</option><option value="group">Tüm Şirketler / Grup Organizasyon Şeması</option></select></label><label className="org-search"><span>Çalışan ara</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ad, sicil, pozisyon veya yönetici"/></label><button className={issues.length?"org-warning":""} onClick={()=>setIssuesOpen(true)}>⚠ Organizasyon Kontrolü · {issues.length}</button></section>
  <section className="module-stats"><article><small>Departman</small><strong>{departments.length}</strong></article><article><small>Tanımlı Pozisyon</small><strong>{positions.length}</strong></article><article><small>Aktif Çalışan</small><strong>{employees.filter(active).length}</strong></article><article><small>Dolu Pozisyon</small><strong>{filled}</strong></article></section>
  <section className="org-filterbar"><select value={departmentFilter} onChange={e=>setDepartmentFilter(e.target.value)}><option value="">Tüm Departmanlar</option>{departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select><select value={positionFilter} onChange={e=>setPositionFilter(e.target.value)}><option value="">Tüm Pozisyonlar</option>{[...new Set(positions.map(p=>p.title))].map(x=><option key={x}>{x}</option>)}</select><select value={managerFilter} onChange={e=>setManagerFilter(e.target.value)}><option value="">Tüm Yöneticiler</option>{[...new Set(employees.map(e=>e.manager).filter(Boolean) as string[])].map(x=><option key={x}>{x}</option>)}</select><select value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">Tüm Personel Tipleri</option>{[...new Set(employees.map(e=>e.employeeType).filter(Boolean) as string[])].map(x=><option key={x}>{x}</option>)}</select><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option>Aktif</option><option value="">Tüm Durumlar</option><option>Pasif</option><option>İzinli</option></select><label className="org-switch"><input type="checkbox" checked={showEmpty} onChange={e=>setShowEmpty(e.target.checked)}/> Boş Pozisyonları Göster</label></section>
  <div className="org-tabs">{([['chart','Organizasyon Şeması'],['departments','Departman Görünümü'],['positions','Pozisyon Görünümü'],['list','Liste Görünümü']] as [View,string][]).map(([k,l])=><button className={view===k?"active":""} onClick={()=>setView(k)} key={k}>{l}</button>)}<span/><button onClick={excel}>Excel</button><button onClick={pdf}>PDF</button><button onClick={png}>PNG</button></div>
  {error&&<div className="form-error">{error}</div>}{loading?<div className="panel loading">Organizasyon yapısı yükleniyor…</div>:view==="chart"?<Chart companies={companies} scope={scope} employees={displayEmployees} positions={positions} roots={roots} direct={direct} selected={setSelected} collapsed={collapsed} toggle={toggle} query={query} zoom={zoom} pan={pan} canvas={canvas} pointerDown={pointerDown} pointerMove={pointerMove} pointerUp={pointerUp} setZoom={setZoom}/>:view==="departments"?<DepartmentView departments={departments} positions={positions} employees={filtered} direct={direct} selected={setSelected} edit={d=>{setEditing(d);setModal("department")}} remove={remove}/>:view==="positions"?<PositionView positions={positions} departments={departments} employees={filtered} showEmpty={showEmpty} selected={setSelected} edit={p=>{setEditing(p);setModal("position")}} remove={remove}/>:<ListView employees={filtered} companies={companies} selected={setSelected}/>}
  {selected&&<Detail employee={selected} manager={managerOf(selected)} reports={direct(selected,employees)} chain={managementChain(selected,employees,managerOf)} close={()=>setSelected(null)}/>} {issuesOpen&&<div className="org-sheet-backdrop" onClick={()=>setIssuesOpen(false)}><aside className="org-detail" onClick={e=>e.stopPropagation()}><header><div><small>VERİ BÜTÜNLÜĞÜ</small><h2>Organizasyon Kontrolü</h2></div><button onClick={()=>setIssuesOpen(false)}>×</button></header>{issues.length?issues.map((i,n)=><button className="org-issue" key={n} onClick={()=>i.employee&&setSelected(i.employee)}><b>{i.kind}</b><span>{i.text}</span></button>):<div className="org-ok">✓ Organizasyon bağlantıları tutarlı.</div>}</aside></div>}
  {copyOpen&&<OrganizationCopyModal close={()=>setCopyOpen(false)} done={async m=>{setCopyOpen(false);await load();act(m)}}/>}{modal&&<Editor kind={modal} editing={editing} departments={departments} positions={positions} submit={submit} close={()=>setModal(null)}/>} </div>
}

function Chart({companies,scope,employees,positions,roots,direct,selected,collapsed,toggle,query,zoom,pan,canvas,pointerDown,pointerMove,pointerUp,setZoom}:{companies:Company[];scope:string;employees:Employee[];positions:Position[];roots:(e:Employee[])=>Employee[];direct:(e:Employee,l?:Employee[])=>Employee[];selected:(e:Employee)=>void;collapsed:Set<number>;toggle:(id:number)=>void;query:string;zoom:number;pan:{x:number;y:number};canvas:RefObject<HTMLDivElement|null>;pointerDown:(e:ReactPointerEvent)=>void;pointerMove:(e:ReactPointerEvent)=>void;pointerUp:()=>void;setZoom:(n:number)=>void}){const blocks=scope==="group"?companies.map(c=>({company:c,list:employees.filter(e=>e.companyId===c.id)})):[{company:null,list:employees}];return <section className="panel org-chart-shell"><div className="org-chart-tools"><span>Yönetici kartlarındaki ▼ / ▶ ile dalları açıp kapatın</span></div><div ref={canvas} className="org-chart-viewport" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}><div className="org-chart-stage" style={{transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>{scope==="group"&&<div className="org-group-root">GRUP ORGANİZASYON ŞEMASI</div>}<div className={scope==="group"?"org-company-branches":""}>{blocks.map(b=><section className="org-company-tree" key={b.company?.id||'active'}>{b.company&&<h3>{b.company.name}</h3>}<div className="org-roots">{roots(b.list).map(e=><OrgNode key={e.id} employee={e} list={b.list} direct={direct} positions={positions} collapsed={collapsed} toggle={toggle} selected={selected} query={query} seen={new Set()}/>)}</div>{!b.list.length&&<p className="org-empty">Bu şirkette görüntülenecek sicil kartı bulunmuyor.</p>}</section>)}</div></div></div><div className="org-zoom"><button onClick={()=>setZoom(Math.min(1.4,zoom+.1))}>＋ Yakınlaştır</button><button onClick={()=>setZoom(Math.max(.45,zoom-.1))}>− Uzaklaştır</button><button onClick={()=>setZoom(.82)}>Ekrana Sığdır</button><button onClick={()=>canvas.current?.requestFullscreen()}>Tam Ekran</button></div></section>}
function OrgNode({employee,list,direct,positions,collapsed,toggle,selected,query,seen}:{employee:Employee;list:Employee[];direct:(e:Employee,l?:Employee[])=>Employee[];positions:Position[];collapsed:Set<number>;toggle:(id:number)=>void;selected:(e:Employee)=>void;query:string;seen:Set<number>}){if(seen.has(employee.id))return null;const next=new Set(seen);next.add(employee.id);const children=direct(employee,list),closed=collapsed.has(employee.id),level=positions.find(p=>p.id===employee.positionId)?.level||employee.position;return <div className="org-tree-node"><div className={`org-person-card ${levelClass(level)} ${query&&norm(`${full(employee)} ${employee.position}`).includes(norm(query))?'highlight':''}`} onClick={()=>selected(employee)}><div className="org-avatar">{employee.firstName?.[0]}{employee.lastName?.[0]}</div><div><strong>{full(employee)}</strong><span>{employee.position||"Pozisyon atanmamış"}</span><small>{employee.department||"Departman atanmamış"}</small>{employee.actingManager&&<em>Vekaleten: {employee.actingManager}</em>}</div>{children.length>0&&<button className="org-node-toggle" data-closed={closed} onClick={e=>{e.stopPropagation();toggle(employee.id)}}>{closed?'▶':'▼'} {children.length}</button>}</div>{children.length>0&&!closed&&<div className="org-children">{children.map(c=><OrgNode key={c.id} employee={c} list={list} direct={direct} positions={positions} collapsed={collapsed} toggle={toggle} selected={selected} query={query} seen={next}/>)}</div>}</div>}
const levelClass=(v:string)=>/genel müdür|ceo|üst yönetim/i.test(v)?"level-1":/direktör|müdür/i.test(v)?"level-2":/yönetici|kıdemli/i.test(v)?"level-3":"level-4";
function DepartmentView({departments,positions,employees,direct,selected,edit,remove}:{departments:Department[];positions:Position[];employees:Employee[];direct:(e:Employee,l?:Employee[])=>Employee[];selected:(e:Employee)=>void;edit:(d:Department)=>void;remove:(k:"department"|"position",id:number,n:string)=>void}){return <section className="org-department-grid">{departments.map(d=>{const staff=employees.filter(e=>e.departmentId===d.id||(!e.departmentId&&e.department===d.name)),managers=staff.filter(e=>direct(e,employees).length>0),open=positions.filter(p=>p.departmentId===d.id&&!employees.some(e=>e.positionId===p.id||e.position===p.title));return <article className="panel org-department-card" key={d.id}><header><div><small>{d.code}</small><h3>{d.name}</h3><p>Yönetici: {d.managerName||managers.map(full).join(', ')||"Atanmamış"}</p></div><div><b>{staff.length}<small>Çalışan</small></b><b>{managers.length}<small>Yönetici</small></b><b>{open.length}<small>Açık</small></b></div></header><div>{staff.map(e=><button key={e.id} onClick={()=>selected(e)}><strong>{full(e)}</strong><span>{e.position}</span></button>)}</div><footer><button onClick={()=>edit(d)}>Düzenle</button><button onClick={()=>remove("department",d.id,d.name)}>Sil</button></footer></article>})}</section>}
function PositionView({positions,departments,employees,showEmpty,selected,edit,remove}:{positions:Position[];departments:Department[];employees:Employee[];showEmpty:boolean;selected:(e:Employee)=>void;edit:(p:Position)=>void;remove:(k:"department"|"position",id:number,n:string)=>void}){return <section className="org-position-grid">{positions.map(p=>({p,people:employees.filter(e=>e.positionId===p.id||(e.departmentId===p.departmentId&&e.position===p.title))})).filter(x=>showEmpty||x.people.length).map(({p,people})=><article className="panel org-position-card" key={p.id}><header><div><small>{p.code} · {p.level}</small><h3>{p.title}</h3><p>{departments.find(d=>d.id===p.departmentId)?.name}</p></div><b className={people.length?"":"vacant"}>{people.length||"BOŞ"}</b></header>{people.map(e=><button key={e.id} onClick={()=>selected(e)}>{full(e)}</button>)}{!people.length&&<p className="org-vacant">● Pozisyon Boş</p>}<footer><button onClick={()=>edit(p)}>Düzenle</button><button onClick={()=>remove("position",p.id,p.title)}>Sil</button></footer></article>)}</section>}
function ListView({employees,companies,selected}:{employees:Employee[];companies:Company[];selected:(e:Employee)=>void}){return <section className="panel org-list"><div className="org-list-row head"><span>Çalışan</span><span>Pozisyon</span><span>Departman</span><span>Yönetici</span><span>Şirket</span></div>{employees.map(e=><button className="org-list-row" key={e.id} onClick={()=>selected(e)}><span><b>{full(e)}</b><small>{e.employeeNo}</small></span><span>{e.position||"—"}</span><span>{e.department||"—"}</span><span>{e.manager||"Atanmamış"}</span><span>{companies.find(c=>c.id===e.companyId)?.name||e.companyId}</span></button>)}</section>}
function managementChain(e:Employee,list:Employee[],managerOf:(e:Employee,l?:Employee[])=>Employee|undefined){const out:Employee[]=[e],seen=new Set([e.id]);let cur=e;for(let i=0;i<12;i++){const m=managerOf(cur,list);if(!m||seen.has(m.id))break;out.push(m);seen.add(m.id);cur=m}return out}
function Detail({employee,manager,reports,chain,close}:{employee:Employee;manager?:Employee;reports:Employee[];chain:Employee[];close:()=>void}){return <div className="org-sheet-backdrop" onClick={close}><aside className="org-detail" onClick={e=>e.stopPropagation()}><header><div><small>PERSONEL SİCİL KARTI</small><h2>{full(employee)}</h2><p>{employee.position}</p></div><button onClick={close}>×</button></header><dl>{[["Sicil No",employee.employeeNo],["Şirket",employee.companyId],["Departman",employee.department],["Pozisyon",employee.position],["Bağlı Olduğu Yönetici",manager?full(manager):employee.manager||"Atanmamış"],["İkinci Yönetici",employee.secondManager||"Atanmamış"],["Vekaleten Yönetici",employee.actingManager||"Yok"],["Kendisine Bağlı",`${reports.length} çalışan`],["İşe Giriş",employee.startDate||"—"],["Personel Tipi",employee.employeeType||"—"]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><section className="org-chain"><h3>Yönetim Hattı</h3>{chain.map((x,i)=><div key={x.id}><b>{full(x)}</b><span>{x.position}</span>{i<chain.length-1&&<i>↓</i>}</div>)}</section></aside></div>}
function Editor({kind,editing,departments,positions,submit,close}:{kind:"department"|"position";editing:Department|Position|null;departments:Department[];positions:Position[];submit:(e:FormEvent<HTMLFormElement>)=>void;close:()=>void}){return <div className="modal-backdrop"><form className="record-modal org-modal" onSubmit={submit}><header><div><span>ORGANİZASYON YAPISI</span><h2>{editing?"Kaydı Düzenle":kind==="department"?"Yeni Departman":"Yeni Pozisyon"}</h2></div><button type="button" onClick={close}>×</button></header><div className="form-grid">{kind==="department"?<><Field label="Departman Adı *" name="name" value={(editing as Department)?.name} required/><Field label="Departman Kodu" name="code" value={(editing as Department)?.code||"Otomatik oluşturulacak"} readOnly/><Select label="Üst Departman" name="parentDepartmentId" value={String((editing as Department)?.parentDepartmentId||"")} options={departments.filter(d=>d.id!==editing?.id).map(d=>({value:String(d.id),label:d.name}))}/><Field label="Departman Yöneticisi" name="managerName" value={(editing as Department)?.managerName}/><Select label="Durum" name="status" value={(editing as Department)?.status||"Aktif"} options={["Aktif","Pasif"]}/></>:<><Field label="Pozisyon Adı *" name="title" value={(editing as Position)?.title} required/><Field label="Pozisyon Kodu" name="code" value={(editing as Position)?.code||"Otomatik oluşturulacak"} readOnly/><Select label="Departman *" name="departmentId" value={String((editing as Position)?.departmentId||"")} required options={departments.map(d=>({value:String(d.id),label:d.name}))}/><Select label="Seviye" name="level" value={(editing as Position)?.level||"Uzman"} options={["Üst Yönetim","Direktör","Müdür","Yönetici","Kıdemli Uzman","Uzman","Uzman Yardımcısı","Destek"]}/><Select label="Bağlı Olduğu Pozisyon" name="reportsToId" value={String((editing as Position)?.reportsToId||"")} options={positions.filter(p=>p.id!==editing?.id).map(p=>({value:String(p.id),label:p.title}))}/></>}</div><footer><button type="button" onClick={close}>İptal</button><button className="primary">Kaydet</button></footer></form></div>}
function Field({label,name,value,required,readOnly}:{label:string;name:string;value?:string;required?:boolean;readOnly?:boolean}){return <label className="field"><span>{label}</span><input name={name} defaultValue={value||""} required={required} readOnly={readOnly}/></label>}
function Select({label,name,value,required,options}:{label:string;name:string;value?:string;required?:boolean;options:(string|{value:string;label:string})[]}){return <label className="field"><span>{label}</span><select name={name} defaultValue={value||""} required={required}><option value="">Seçiniz</option>{options.map(o=>typeof o==="string"?<option key={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></label>}
