"use client";
import {useEffect,useMemo,useState} from "react";
type Company={id:string;name:string};type Department={id:number;name:string;parentDepartmentId?:number|null};type Position={id:number;departmentId:number;title:string};
export default function OrganizationCopyModal({close,done}:{close:()=>void;done:(message:string)=>void}){
 const[companies,setCompanies]=useState<Company[]>([]),[source,setSource]=useState(""),[target,setTarget]=useState(""),[departments,setDepartments]=useState<Department[]>([]),[positions,setPositions]=useState<Position[]>([]),[selectedDepartments,setSelectedDepartments]=useState<number[]>([]),[selectedPositions,setSelectedPositions]=useState<number[]>([]),[includePositions,setIncludePositions]=useState(true),[policy,setPolicy]=useState("skip"),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{const active=document.cookie.match(/(?:^|;\s*)mega_company=([^;]+)/)?.[1]||"mega-global-energy";setTarget(decodeURIComponent(active));fetch("/api/companies").then(r=>r.json()).then(j=>setCompanies(j.companies||[]))},[]);
 useEffect(()=>{if(!source){setDepartments([]);setPositions([]);return}setLoading(true);fetch(`/api/organization/copy?sourceCompanyId=${encodeURIComponent(source)}&company=${encodeURIComponent(target)}`).then(async r=>({ok:r.ok,data:await r.json()})).then(({ok,data})=>{if(!ok)throw new Error(data.error);setDepartments(data.departments||[]);setPositions(data.positions||[]);setSelectedDepartments((data.departments||[]).map((d:Department)=>d.id));setSelectedPositions((data.positions||[]).map((p:Position)=>p.id));setError("")}).catch(e=>setError(e.message||"Organizasyon yapısı alınamadı")).finally(()=>setLoading(false))},[source,target]);
 const sourceCompany=companies.find(c=>c.id===source),targetCompany=companies.find(c=>c.id===target),positionCount=useMemo(()=>positions.filter(p=>selectedDepartments.includes(p.departmentId)&&selectedPositions.includes(p.id)).length,[positions,selectedDepartments,selectedPositions]);
 const toggle=(list:number[],set:(v:number[])=>void,id:number)=>set(list.includes(id)?list.filter(x=>x!==id):[...list,id]);
 async function copy(){if(!source||!target||!selectedDepartments.length){setError("Kaynak şirket ve en az bir departman seçilmelidir.");return}setLoading(true);const r=await fetch("/api/organization/copy",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceCompanyId:source,targetCompanyId:target,departmentIds:selectedDepartments,positionIds:selectedPositions,includePositions,policy})}),j=await r.json();setLoading(false);if(!r.ok){setError(j.error||"Kopyalama tamamlanamadı");return}done(`${j.summary.departments.created} departman ve ${j.summary.positions.created} pozisyon kopyalandı. ${j.summary.departments.existing+j.summary.positions.existing} mevcut kayıt yeniden oluşturulmadı.`)}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="record-modal org-copy-modal"><header><div><span>ŞİRKETLER ARASI ORGANİZASYON</span><h2>Başka Şirketten Kopyala</h2><p>Departman ve pozisyonları personel kayıtlarına dokunmadan hedef şirkete kopyalayın.</p></div><button onClick={close}>×</button></header><div className="copy-company-grid"><label className="field"><span>Kaynak Şirket *</span><select value={source} onChange={e=>setSource(e.target.value)}><option value="">Seçiniz</option>{companies.filter(c=>c.id!==target).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Hedef Şirket</span><select value={target} onChange={e=>setTarget(e.target.value)}>{companies.filter(c=>c.id!==source).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label></div>{source&&<div className="copy-summary"><strong>{sourceCompany?.name}</strong><span>→</span><strong>{targetCompany?.name}</strong><small>{selectedDepartments.length} departman · {includePositions?positionCount:0} pozisyon</small></div>}<div className="copy-options"><label><input type="checkbox" checked={includePositions} onChange={e=>setIncludePositions(e.target.checked)}/> Departmanlara bağlı pozisyonları da kopyala</label><label>Tekrarlı kayıt<select value={policy} onChange={e=>setPolicy(e.target.value)}><option value="skip">Atla</option><option value="use">Mevcut kaydı kullan</option><option value="update">Mevcut kaydı güncelle</option></select></label></div>{loading&&!departments.length?<div className="loading">Organizasyon yapısı yükleniyor…</div>:<div className="copy-list">{departments.map(d=>{const childPositions=positions.filter(p=>p.departmentId===d.id);return <article key={d.id}><label><input type="checkbox" checked={selectedDepartments.includes(d.id)} onChange={()=>toggle(selectedDepartments,setSelectedDepartments,d.id)}/><strong>{d.name}</strong><small>{childPositions.length} pozisyon</small></label>{includePositions&&selectedDepartments.includes(d.id)&&<div>{childPositions.map(p=><label key={p.id}><input type="checkbox" checked={selectedPositions.includes(p.id)} onChange={()=>toggle(selectedPositions,setSelectedPositions,p.id)}/><span>{p.title}</span></label>)}</div>}</article>})}</div>}{error&&<div className="form-error">{error}</div>}<footer><button onClick={close}>İptal</button><button className="primary" disabled={loading||!source} onClick={copy}>{loading?"Kopyalanıyor…":"Seçilenleri Kopyala"}</button></footer></section></div>
}
