export type Weights={goalWeight:number;kpiWeight:number;competencyWeight:number;managerWeight:number;selfWeight:number;feedback360Weight:number};
export function validateWeights(w:Weights){return Object.values(w).reduce((s,x)=>s+Number(x||0),0)===100}
export function metricScore(direction:string,target:number,actual:number,min=0,max=0){if(direction==="Manuel değerlendirme")return Math.max(0,Math.min(100,actual));if(direction==="Düşük değer iyi")return actual<=0?100:Math.max(0,Math.min(100,Math.round(target/actual*100)));if(direction==="Hedef aralığı iyi")return actual>=min&&actual<=max?100:Math.max(0,Math.min(100,Math.round(actual<min?actual/min*100:max/actual*100)));if(direction==="Eşit hedef")return actual===target?100:Math.max(0,100-Math.round(Math.abs(actual-target)/Math.max(1,target)*100));return Math.max(0,Math.min(100,Math.round(actual/Math.max(1,target)*100)))}
export function goalResult(direction:string,target:number,actual:number,weight:number,cap=120){let raw=0;if(direction==="Düşük değer iyi")raw=actual<=0?cap:Math.round(target/actual*100);else if(direction==="Hedef değere yakınlık")raw=Math.max(0,100-Math.round(Math.abs(actual-target)/Math.max(1,target)*100));else if(direction==="Evet/Hayır"||direction==="Tamamlandı/Tamamlanmadı")raw=actual>0?100:0;else raw=Math.round(actual/Math.max(1,target)*100);const score=Math.max(0,Math.min(cap,raw));return{rawProgress:Math.max(0,raw),score,weightedContribution:Math.round(score*weight)/100}}
export function goalRisk(startDate:string,endDate:string,progress:number,today=new Date().toISOString().slice(0,10)){if(!endDate)return{riskLevel:"Kontrol Gerekli",status:"Taslak"};if(today>endDate&&progress<100)return{riskLevel:"Gecikmiş",status:"Başarısız"};if(progress>=100)return{riskLevel:"Normal",status:"Tamamlandı"};if(!startDate||today<startDate)return{riskLevel:"Normal",status:"Onaylandı"};const elapsed=new Date(today).getTime()-new Date(startDate).getTime(),total=Math.max(1,new Date(endDate).getTime()-new Date(startDate).getTime()),period=Math.max(0,Math.min(1,elapsed/total));return period>=.75&&progress<30?{riskLevel:"Riskli",status:"Riskli"}:{riskLevel:"Normal",status:"Devam Ediyor"}}
export function weightedAverage(items:{score:number;weight:number}[]){const total=items.reduce((s,x)=>s+x.weight,0);return total?Math.round(items.reduce((s,x)=>s+x.score*x.weight,0)/total):0}
export function overallScore(scores:{goal:number;kpi:number;competency:number;manager:number;self:number;feedback360:number},w:Weights){return Math.round((scores.goal*w.goalWeight+scores.kpi*w.kpiWeight+scores.competency*w.competencyWeight+scores.manager*w.managerWeight+scores.self*w.selfWeight+scores.feedback360*w.feedback360Weight)/100)}
export function availableOverallScore(scores:{goal:number;kpi:number;competency:number;manager:number;self:number;feedback360:number},w:Weights,available:Partial<Record<keyof typeof scores,boolean>>){const keys=(Object.keys(scores) as (keyof typeof scores)[]).filter(k=>available[k]&&w[`${k}Weight` as keyof Weights]>0),weight=keys.reduce((sum,k)=>sum+w[`${k}Weight` as keyof Weights],0);return weight?Math.round(keys.reduce((sum,k)=>sum+scores[k]*w[`${k}Weight` as keyof Weights],0)/weight):0}
export function performanceClass(score:number){return score>=90?"A Grubu – Üstün Performans":score>=80?"B Grubu – Beklentinin Üzerinde":score>=70?"C Grubu – Beklentiyi Karşılıyor":score>=60?"D Grubu – Gelişim Gerekli":"E Grubu – Yetersiz Performans"}
export function monthsBetween(start:string,end=new Date().toISOString().slice(0,10)){const a=new Date(start+"T12:00:00"),b=new Date(end+"T12:00:00");return Math.max(0,(b.getFullYear()-a.getFullYear())*12+b.getMonth()-a.getMonth()-(b.getDate()<a.getDate()?1:0))}
export function smartAssessment(input:{name:string;description?:string;targetValue?:number;unit?:string;startDate?:string;endDate?:string}){const text=`${input.name||""} ${input.description||""}`.trim(),checks={specific:text.length>=20,measurable:Number(input.targetValue)>0&&Boolean(input.unit),achievable:Number.isFinite(Number(input.targetValue))&&Number(input.targetValue)>0,relevant:text.length>=30,timeBound:Boolean(input.startDate&&input.endDate&&input.endDate>=input.startDate)},score=Object.values(checks).filter(Boolean).length*20;return{checks,score,valid:checks.specific&&checks.measurable&&checks.timeBound,message:score===100?"SMART hedef uygun":"Hedefi ölçülebilir, açıklayıcı ve tarihli hale getirin"}}
